AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Lambda function for routines management with DynamoDB integration

Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  RoutinesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Routines
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  RoutinesManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RoutinesManager
      PackageType: Image
      ImageConfig:
        Command: ["src.handlers.routine_handler.lambda_handler"]
      Environment:
        Variables:
          ROUTINES_TABLE: !Ref RoutinesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RoutinesTable
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.11-v1

Outputs:
  RoutinesFunction:
    Description: Routines Lambda Function ARN
    Value: !GetAtt RoutinesManagerFunction.Arn 